################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
utils \
src/wimax/test \
src/wimax/model \
src/wimax/helper \
src/wimax/examples \
src/wifi/test \
src/wifi/model \
src/wifi/helper \
src/wifi/examples \
src/wave/test \
src/wave/model \
src/wave/helper \
src/wave/examples \
src/visualizer/model \
src/virtual-net-device/model \
src/virtual-net-device/examples \
src/uan/test \
src/uan/model \
src/uan/helper \
src/uan/examples \
src/traffic-control/test \
src/traffic-control/model \
src/traffic-control/helper \
src/traffic-control/examples \
src/topology-read/test \
src/topology-read/model \
src/topology-read/helper \
src/topology-read/examples \
src/test/traced \
src/test/perf \
src/test/ns3wifi \
src/test/ns3tcp \
src/test/ns3tc \
src/test \
src/tap-bridge/model \
src/tap-bridge/helper \
src/tap-bridge/examples \
src/stats/test \
src/stats/model \
src/stats/helper \
src/stats/examples \
src/spectrum/test \
src/spectrum/model \
src/spectrum/helper \
src/spectrum/examples \
src/sixlowpan/test \
src/sixlowpan/model \
src/sixlowpan/helper \
src/sixlowpan/examples \
src/propagation/test \
src/propagation/model \
src/propagation/examples \
src/point-to-point-layout/model \
src/point-to-point/test \
src/point-to-point/model \
src/point-to-point/helper \
src/point-to-point/examples \
src/openflow/test \
src/openflow/model \
src/openflow/helper \
src/openflow/examples \
src/olsr/test \
src/olsr/model \
src/olsr/helper \
src/olsr/examples \
src/nix-vector-routing/model \
src/nix-vector-routing/helper \
src/nix-vector-routing/examples \
src/network/utils \
src/network/test \
src/network/model \
src/network/helper \
src/network/examples \
src/netanim/test \
src/netanim/model \
src/netanim/examples \
src/mpi/model \
src/mpi/examples \
src/mobility/test \
src/mobility/model \
src/mobility/helper \
src/mobility/examples \
src/mesh/test \
src/mesh/test/flame \
src/mesh/test/dot11s \
src/mesh/model \
src/mesh/model/flame \
src/mesh/model/dot11s \
src/mesh/helper \
src/mesh/helper/flame \
src/mesh/helper/dot11s \
src/mesh/examples \
src/lte/test \
src/lte/model \
src/lte/helper \
src/lte/examples \
src/lr-wpan/test \
src/lr-wpan/model \
src/lr-wpan/helper \
src/lr-wpan/examples \
src/internet-apps/test \
src/internet-apps/model \
src/internet-apps/helper \
src/internet-apps/examples \
src/internet/test \
src/internet/model \
src/internet/helper \
src/internet/examples \
src/flow-monitor/test \
src/flow-monitor/model \
src/flow-monitor/helper \
src/fd-net-device/model \
src/fd-net-device/helper \
src/fd-net-device/examples \
src/energy/test \
src/energy/model \
src/energy/helper \
src/energy/examples \
src/dsr/test \
src/dsr/model \
src/dsr/helper \
src/dsr/examples \
src/dsdv/test \
src/dsdv/model \
src/dsdv/helper \
src/dsdv/examples \
src/csma-layout/model \
src/csma-layout/examples \
src/csma/model \
src/csma/helper \
src/csma/examples \
src/core/test \
src/core/model \
src/core/helper \
src/core/examples \
src/core/bindings \
src/config-store/model \
src/config-store/examples \
src/click/test \
src/click/model \
src/click/helper \
src/click/examples \
src/buildings/test \
src/buildings/model \
src/buildings/helper \
src/buildings/examples \
src/brite/test \
src/brite/helper \
src/brite/examples \
src/bridge/model \
src/bridge/helper \
src/bridge/examples \
src/applications/test \
src/applications/model \
src/applications/helper \
src/aodv/test \
src/aodv/model \
src/aodv/helper \
src/aodv/examples \
src/antenna/test \
src/antenna/model \
scratch/subdir \
scratch \
examples/wireless \
examples/udp-client-server \
examples/udp \
examples/tutorial \
examples/traffic-control \
examples/tcp \
examples/stats \
examples/socket \
examples/routing \
examples/realtime \
examples/naming \
examples/matrix-topology \
examples/ipv6 \
examples/error-model \
examples/energy \
build/utils \
build/src/wimax/test \
build/src/wimax/model \
build/src/wimax/helper \
build/src/wimax/examples \
build/src/wimax/bindings \
build/src/wifi/test \
build/src/wifi/model \
build/src/wifi/helper \
build/src/wifi/examples \
build/src/wifi/bindings \
build/src/wave/test \
build/src/wave/model \
build/src/wave/helper \
build/src/wave/examples \
build/src/wave/bindings \
build/src/visualizer/model \
build/src/visualizer/bindings \
build/src/virtual-net-device/model \
build/src/virtual-net-device/examples \
build/src/virtual-net-device/bindings \
build/src/uan/test \
build/src/uan/model \
build/src/uan/helper \
build/src/uan/examples \
build/src/uan/bindings \
build/src/traffic-control/test \
build/src/traffic-control/model \
build/src/traffic-control/helper \
build/src/traffic-control/examples \
build/src/traffic-control/bindings \
build/src/topology-read/test \
build/src/topology-read/model \
build/src/topology-read/helper \
build/src/topology-read/examples \
build/src/topology-read/bindings \
build/src/test/traced \
build/src/test/ns3wifi \
build/src/test/ns3tcp \
build/src/test/ns3tc \
build/src/test \
build/src/tap-bridge/model \
build/src/tap-bridge/helper \
build/src/tap-bridge/examples \
build/src/tap-bridge/bindings \
build/src/stats/test \
build/src/stats/model \
build/src/stats/helper \
build/src/stats/examples \
build/src/stats/bindings \
build/src/spectrum/test \
build/src/spectrum/model \
build/src/spectrum/helper \
build/src/spectrum/examples \
build/src/spectrum/bindings \
build/src/sixlowpan/test \
build/src/sixlowpan/model \
build/src/sixlowpan/helper \
build/src/sixlowpan/examples \
build/src/sixlowpan/bindings \
build/src/propagation/test \
build/src/propagation/model \
build/src/propagation/examples \
build/src/propagation/bindings \
build/src/point-to-point-layout/model \
build/src/point-to-point-layout/bindings \
build/src/point-to-point/test \
build/src/point-to-point/model \
build/src/point-to-point/helper \
build/src/point-to-point/examples \
build/src/point-to-point/bindings \
build/src/olsr/test \
build/src/olsr/model \
build/src/olsr/helper \
build/src/olsr/examples \
build/src/olsr/bindings \
build/src/nix-vector-routing/model \
build/src/nix-vector-routing/helper \
build/src/nix-vector-routing/examples \
build/src/nix-vector-routing/bindings \
build/src/network/utils \
build/src/network/test \
build/src/network/model \
build/src/network/helper \
build/src/network/examples \
build/src/network/bindings \
build/src/netanim/test \
build/src/netanim/model \
build/src/netanim/examples \
build/src/mpi/model \
build/src/mpi/examples \
build/src/mpi/bindings \
build/src/mobility/test \
build/src/mobility/model \
build/src/mobility/helper \
build/src/mobility/examples \
build/src/mobility/bindings \
build/src/mesh/test \
build/src/mesh/test/flame \
build/src/mesh/test/dot11s \
build/src/mesh/model \
build/src/mesh/model/flame \
build/src/mesh/model/dot11s \
build/src/mesh/helper \
build/src/mesh/helper/flame \
build/src/mesh/helper/dot11s \
build/src/mesh/examples \
build/src/mesh/bindings \
build/src/lte/test \
build/src/lte/model \
build/src/lte/helper \
build/src/lte/examples \
build/src/lte/bindings \
build/src/lr-wpan/test \
build/src/lr-wpan/model \
build/src/lr-wpan/helper \
build/src/lr-wpan/examples \
build/src/lr-wpan/bindings \
build/src/internet-apps/test \
build/src/internet-apps/model \
build/src/internet-apps/helper \
build/src/internet-apps/examples \
build/src/internet-apps/bindings \
build/src/internet/test \
build/src/internet/model \
build/src/internet/helper \
build/src/internet/examples \
build/src/internet/bindings \
build/src/flow-monitor/test \
build/src/flow-monitor/model \
build/src/flow-monitor/helper \
build/src/flow-monitor/bindings \
build/src/fd-net-device/model \
build/src/fd-net-device/helper \
build/src/fd-net-device/examples \
build/src/fd-net-device/bindings \
build/src/energy/test \
build/src/energy/model \
build/src/energy/helper \
build/src/energy/examples \
build/src/energy/bindings \
build/src/dsr/test \
build/src/dsr/model \
build/src/dsr/helper \
build/src/dsr/examples \
build/src/dsr/bindings \
build/src/dsdv/test \
build/src/dsdv/model \
build/src/dsdv/helper \
build/src/dsdv/examples \
build/src/dsdv/bindings \
build/src/csma-layout/model \
build/src/csma-layout/examples \
build/src/csma-layout/bindings \
build/src/csma/model \
build/src/csma/helper \
build/src/csma/examples \
build/src/csma/bindings \
build/src/core/test \
build/src/core/model \
build/src/core/helper \
build/src/core/examples \
build/src/core/bindings \
build/src/config-store/model \
build/src/config-store/examples \
build/src/config-store/bindings \
build/src/buildings/test \
build/src/buildings/model \
build/src/buildings/helper \
build/src/buildings/examples \
build/src/buildings/bindings \
build/src/bridge/model \
build/src/bridge/helper \
build/src/bridge/examples \
build/src/bridge/bindings \
build/src/applications/test \
build/src/applications/model \
build/src/applications/helper \
build/src/applications/bindings \
build/src/aodv/test \
build/src/aodv/model \
build/src/aodv/helper \
build/src/aodv/examples \
build/src/aodv/bindings \
build/src/antenna/test \
build/src/antenna/model \
build/src/antenna/bindings \
build/scratch/subdir \
build/scratch \
build/examples/wireless \
build/examples/udp-client-server \
build/examples/udp \
build/examples/tutorial \
build/examples/traffic-control \
build/examples/tcp \
build/examples/stats \
build/examples/socket \
build/examples/routing \
build/examples/realtime \
build/examples/naming \
build/examples/matrix-topology \
build/examples/ipv6 \
build/examples/error-model \
build/examples/energy \
bindings/python \

